# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [3]:
#Solution
import numpy as np
numpy_array = np.random.randint(10,24,24)
print(numpy_array)
print(len(numpy_array))


[22 12 15 19 17 11 11 16 21 10 16 14 17 12 22 21 17 11 13 11 11 20 20 20]
24


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [4]:
# Solution
import numpy as np
numpy_array_two = np.arange(1,50,3)
print(numpy_array_two)
print(len(numpy_array_two))



[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
17


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [5]:
# Solution
import numpy as nnp
numpy_array_three = nnp.linspace(4,7,27)
print(numpy_array_three)
print(len(numpy_array_three))



[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]
27


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [6]:
# Solution
import numpy as np
float_matrix_one = np.random.rand(5,4)
print(float_matrix_one)
float_matrix_two = np.round(float_matrix_one,2)
print(float_matrix_two)

[[0.11522183 0.31002849 0.02836417 0.59625034]
 [0.72881042 0.38300174 0.80859981 0.63067442]
 [0.73455354 0.02850896 0.15915696 0.71597957]
 [0.12441181 0.88951102 0.02047224 0.59384693]
 [0.66099917 0.75919434 0.42533062 0.65413215]]
[[0.12 0.31 0.03 0.6 ]
 [0.73 0.38 0.81 0.63]
 [0.73 0.03 0.16 0.72]
 [0.12 0.89 0.02 0.59]
 [0.66 0.76 0.43 0.65]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [7]:
# Solution
np.random.randint(5,16,(5,5))




array([[15, 14,  8, 14, 15],
       [15,  6,  5,  6, 14],
       [11,  5,  5,  8,  9],
       [15, 10, 11,  7, 10],
       [15, 13,  7,  7, 14]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [8]:
# Solution
zero_array = np.zeros(30).astype(int)
print(zero_array)
print(zero_array.dtype)





[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
int32


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [9]:
# Solution
one_array = np.ones((4,5))
one_array_converted = np.float32(one_array)
print(one_array_converted)
print(one_array_converted.shape)
print(one_array_converted.dtype)




[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)
float32


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [12]:
# Solution
matrix_Array_one = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
matrix_Array_one




array([[ 9, 25, 50, 34, 45],
       [ 3, 34, 34, 65,  2],
       [ 5,  7,  3, 76,  3],
       [ 7,  8,  6, 54,  6],
       [23, 12,  8,  5,  8]])

#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [13]:
# Solution
print(matrix_Array_one[2:3,2:3])


[[3]]


#### 10. Print the all the elements of 3rd row of the matrix

In [14]:
# Solution
print(matrix_Array_one[2,])



[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [15]:
# Solution
print(matrix_Array_one[:,3])



[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [16]:
# Solution
print("First Corner : ",matrix_Array_one[0,0])
print("Second Corner : ",matrix_Array_one[0,4])
print("Third Corner : ",matrix_Array_one[4,0])
print("Fourth Corner : ",matrix_Array_one[4,4])



First Corner :  9
Second Corner :  45
Third Corner :  23
Fourth Corner :  8


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [17]:
# Solution 
m1 = matrix_Array_one[0:2,2:4]
print(m1)

m2 = matrix_Array_one[3:5,0:2]
print(m2)

m3 = matrix_Array_one[2:5,2:5]
print(m3)

[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [18]:
# Solution
m1_reshape = m1.reshape(4,)
m2_reshape = m2.reshape(4,)
m3_reshape = m3.reshape(9,)
print(m1_reshape)
print(m2_reshape)
print(m3_reshape)



[50 34 34 65]
[ 7  8 23 12]
[ 3 76  3  6 54  6  8  5  8]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [19]:
# Solution
print(m1)
print(m2)
vertical_matrix = np.concatenate((m1,m2),axis=1)
print(" ")
print("horizontal")
print(vertical_matrix)
horizontal_matrix = np.concatenate((m1,m2))
print(" ")
print("vertical")
print(horizontal_matrix)



[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
 
horizontal
[[50 34  7  8]
 [34 65 23 12]]
 
vertical
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [20]:
# Solution
added_matrix = m1+m2
subtracted_matrix = m1-m2
multiplied_matrix = m1*m2
divided_matrix = m1/m2

print(added_matrix)
print(subtracted_matrix)
print(multiplied_matrix)
print(divided_matrix)



[[57 42]
 [57 77]]
[[43 26]
 [11 53]]
[[350 272]
 [782 780]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [21]:
# Solution
added_matrix = m1+m3[1:,:2]
m3 = m3[1:,:2]
print("Added matrix after removing first row and last column in m3 : ")
print(added_matrix)



Added matrix after removing first row and last column in m3 : 
[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [22]:
# Solution
#print(m1)
me1 = m1[:,0:1].mean(axis=0)
me2 = m1[:,1:].mean(axis=0)
print(me1)
print(me2)
m4 = np.concatenate((me1,me2))
m4 = m4.reshape(2,1)
print(m4.shape)
print(m4)





[42.]
[49.5]
(2, 1)
[[42. ]
 [49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [23]:
# Solution
m3*m4



array([[ 252. , 2268. ],
       [ 396. ,  247.5]])

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [11]:
# Solution
import numpy as np
matrix_Array_one = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
#print(matrix_Array_one)
mean_one = matrix_Array_one.sum(axis=1)
mean_final = (mean_one/5)
#print(mean_final)
print("Maximun Mean")
print(mean_final.max())
print("Minimum Mean")
print(mean_final.min())
print(" ")
var_one = matrix_Array_one.var(axis=1)
#print(var_one)
var_one_max = var_one.max()
var_one_min = var_one.min()
print("Maximum Varience")
print(var_one_max)
print("Minimum Varience")
print(var_one_min)
print(" ")
std_one = np.std(matrix_Array_one,axis=1)
std_one_max = std_one.max()
std_one_min = std_one.min()
print("Maximum Standard Deviation")
print(std_one_max)
print("Minimum Standard Deviation")
print(std_one_min)





Maximun Mean
32.6
Minimum Mean
11.2
 
Maximum Varience
820.1600000000001
Minimum Varience
39.760000000000005
 
Maximum Standard Deviation
28.63843571147
Minimum Standard Deviation
6.305553108173779


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [43]:
# Solution
runs_matrix = np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls_faced_matrix = np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])
run_matrix_avg = runs_matrix.mean(axis=1)
run_matrix_asc = np.sort(run_matrix_avg)
print("Decending order of Runs Average")
print(run_matrix_asc[::-1])
print("")
strike_rate_one = (runs_matrix.sum(axis=1)/balls_faced_matrix.sum(axis=1))*100
strike_rate_vartwo = np.sort(strike_rate_one)
strike_rate_desc = strike_rate_vartwo[::-1]
print("Decending order of Strike Rate")
print(strike_rate_desc)






Decending order of Runs Average
[53.5  51.5  47.25 29.   13.25]

Decending order of Strike Rate
[161.11111111 101.42180095  98.4375      94.93087558  49.53271028]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [49]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
print("Number of Students Passed")
print(len(marks[marks>=50]))
print("")
print("Number of Students Failed")
print(len(marks[marks<50]))




Number of Students Passed
7

Number of Students Failed
3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [76]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
marks_one = np.array([65,84,47,56,89,98,48,77,80,39])
marks_grace = np.where((marks>45) & (marks<49))
marks_one[marks_grace] = marks[marks_grace]+5
#print(marks)
#print(marks_one)
marks_grace_two = np.where(marks_one>80)
marks_one[marks_grace_two] = marks_one[marks_grace_two]+5
#print(marks_one)
marks_hund = np.where(marks_one>100)
marks_one[marks_hund] = 100
print("Students marks after grace points : ")
print(marks_one)
original_percentage = (marks.sum(axis=0)/1000)*100
second_percentage = (marks_one.sum(axis=0)/1000)*100
print("Before Grace Marks Pass Percentage :",original_percentage,"%")
print("After Grace Marks Pass Percentage : ",second_percentage,"%")
print("The pass percentage is improved by : ",second_percentage - original_percentage,"%")

Students marks after grace points : 
[ 65  89  52  56  94 100  53  77  80  39]
Before Grace Marks Pass Percentage : 68.30000000000001 %
After Grace Marks Pass Percentage :  70.5 %
The pass percentage is improved by :  2.1999999999999886 %


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [16]:
# Solution
import time
start = time.time()
for i in range(60000):
    x = i
    y=i+1
    abc = ((x*(i**2))+8)/y*i
    #print(abc)
    #print(x)
    #print(y)
end = time.time()
print("Total Time Taken",end-start)



Total Time Taken 0.04192948341369629


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
# Solution

#Numpy is a package which can be used to create and work with one dimensional and two dimensional arrays.
#There are a few syntax and pre defined matehmatical functions which can be used instead of general python function, this could reduce the number of lines of codes while comparing with usual python functions.
# There are a few disadvantages in numpy where at times we have to change the shape of the matrix at times to make it combine and work with other matrix and functions which could be a tedious process, but while comparing with raw python using numpy is far better in case of predefined functions.


